name: UA Auto-Updater
on:
  workflow_dispatch:  # ম্যানুয়াল রানের জন্য
  schedule:
    - cron: '0 12 * * *'  # দৈনিক বাংলাদেশ সময় ১২টায়

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # রিপোজিটরিতে লিখার পারমিশন

    steps:
      - uses: actions/checkout@v4

      - name: Generate UA Data
        run: |
          # Python স্ক্রিপ্ট রান করবে (সমস্ত ২৫ ডিভাইস ব্যবহার করে)
          python3 new_user.py > ua_data.json

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update UA: $(date +'%d-%m-%Y %H:%M')"
          git push
