name: Auto UA Generator
on:
  schedule:
    - cron: '0 0 * * *'  # প্রতিদিন 12AM বাংলাদেশ সময়
  workflow_dispatch:  # ম্যানুয়ালি রান করার অপশন

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Run UA Generator
        run: |
          python ua_generator.py
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ua_*.json
          git commit -m "Auto: Daily UA Update [$(date +'%d-%m-%Y')]"
          git push
