name: UA Auto-Updater
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    permissions: 
      contents: write  # লেখার পারমিশন যোগ করুন
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate UA Data
        run: |
          echo '{
            "timestamp": "$(date)",
            "user_agents": [
              "Mozilla/5.0 (iPhone16,1; CPU iPhone OS 17_$((RANDOM%5+1)))",
              "Mozilla/5.0 (Linux; Android 13; SM-S918U)"
            ]
          }' > ua_data.json

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update UA: $(date)"
          git push
